baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ye's ML Cafe"


[menu]

  [[menu.main]]
      name = "Home"
      weight = 1
      identifier = "home"
      url = "/"

  [[menu.main]]
      name = "About"
      weight = 2
      identifier = "about"
      url = "/about/"

[params]
  mainSections = ["posts", "docs"]
